[Instruments]
std = 2182A
dut = 2182A

[GPIB]
;endereco da fonte AC
ac_source = 5
;endereco dos dvms
std = 7
dut = 23
;endereco da chave automatizada
sw = 10

[Measurement Config]
; resistencia do dut e do std
; necessario para configurar a fonte
r_dut = 4000 
r_std = 1000
;tempo de espera
wait_time = 60
;tempo de aquecimento (em segundos)
aquecimento = 60
;aquecimento = 36000
;quantidade de repeticoes
repeticoes = 12 
;tensao
;voltage = 0.8
voltage = 5
;frequencia (MHz)
frequency = 1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50
;frequency = 1
[Misc]
;incluir as observacoes pertinentes (opcional)
observacoes = teste A55-5V X A55-20V @ 5 V.
